spring:

  # .env import
  config:
    import: optional:file:.env[.properties]

  application:
    name: crewin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}
      database: ${MONGO_DB}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 50
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    stack:
      auto: false

image:
  prefix: ${S3_IMAGE_PREFIX}
  folder: crewin/
  default:
    session-poster: ${S3_IMAGE_PREFIX}/crewin/SessionPoster.webp
    member-profile: ${S3_IMAGE_PREFIX}/crewin/default-profile.webp
    crew-main-logo: ${S3_IMAGE_PREFIX}/crewin/crewinlogo.webp
    crew-sub-logo: ${S3_IMAGE_PREFIX}/crewin/crewinsublogo.webp
    crew-banner: ${S3_IMAGE_PREFIX}/crewin/banner.webp

security:
  secret-key: ${SECURITY_SECRET_KEY}

frontend:
  server:
    url: ${FRONTEND_URL}

t-map:
  api:
    url: https://apis.openapi.sk.com/tmap
    appKey: ${TMAP_API_KEY}

logging:
  level:
    root: INFO
    com.your.package: DEBUG
  file:
    name: ./logs/crewin_springboot.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/crewin_springboot-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB
